# Generated by Django 4.2.7 on 2023-11-20 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
